import nodemailer from "nodemailer";

export async function sendAlertEmail(
    to: string,
    subject: string,
    html: string
) {
    const transporter = nodemailer.createTransport({
        host: process.env.SMTP_HOST || "smtp.gmail.com",
        port: Number(process.env.SMTP_PORT) || 587,
        secure: false,
        auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASS,
        },
    });

    await transporter.sendMail({
        from: process.env.ALERT_FROM || "alerts@smartdwell.in",
        to,
        subject,
        html,
    });
}

export function buildAlertEmailHtml(
    mac: string,
    currentTemp: number,
    setpoint: number,
    timestamp: string
): string {
    return `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #1a1a2e; color: #e0e0e0; border-radius: 12px; overflow: hidden;">
      <div style="background: linear-gradient(135deg, #e74c3c, #c0392b); padding: 24px; text-align: center;">
        <h1 style="margin: 0; color: white; font-size: 24px;">🌡️ Temperature Alert</h1>
      </div>
      <div style="padding: 24px;">
        <div style="background: rgba(231,76,60,0.15); border: 1px solid rgba(231,76,60,0.3); border-radius: 8px; padding: 16px; margin-bottom: 16px;">
          <p style="margin: 0; font-size: 18px; color: #e74c3c; font-weight: 600;">
            Temperature exceeded setpoint!
          </p>
        </div>
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 8px 0; color: #888;">Device MAC</td>
            <td style="padding: 8px 0; text-align: right; font-weight: 600;">${mac}</td>
          </tr>
          <tr>
            <td style="padding: 8px 0; color: #888;">Current Temperature</td>
            <td style="padding: 8px 0; text-align: right; font-weight: 600; color: #e74c3c;">${currentTemp}°C</td>
          </tr>
          <tr>
            <td style="padding: 8px 0; color: #888;">Setpoint</td>
            <td style="padding: 8px 0; text-align: right; font-weight: 600;">${setpoint}°C</td>
          </tr>
          <tr>
            <td style="padding: 8px 0; color: #888;">Timestamp</td>
            <td style="padding: 8px 0; text-align: right; font-weight: 600;">${timestamp}</td>
          </tr>
        </table>
        <p style="margin-top: 20px; font-size: 13px; color: #666; text-align: center;">
          This alert was generated by Smartdwell IoT Monitor
        </p>
      </div>
    </div>
  `;
}
